[package]
name = "apple-me-curry"
version = "0.0.0"
edition = "2021"
description = "Simple curry function using apply."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
